CREATE TABLE IF NOT EXISTS tara
(
	fid SERIAL PRIMARY KEY,
	nume VARCHAR(50) UNIQUE NOT NULL,
	indicativ VARCHAR(5) NOT NULL,
	suprafata DECIMAL NULL
);

CREATE TABLE IF NOT EXISTS judete
(
	fid SERIAL PRIMARY KEY,
	nume VARCHAR(50) UNIQUE NOT NULL,
	indicativ VARCHAR(5) NOT NULL,
	suprafata DECIMAL NULL,
	tara_fid INTEGER NOT NULL REFERENCES tara(fid)
);


